name: 'Database Lab: realistic DB testing in CI'
branding:
  icon: 'database'  
  color: 'orange'
description: 'Check database migrations with the Database Lab Engine'

outputs:
  response:
    value: Done
    description: 'The result of migration checks'

runs:
  using: 'composite'
  steps:
    - name: DB migration with DLE
      uses: postgres-ai/dle-github-actions/core@composite-action

    - run: |
        echo 'SUMMARY<<EOF' >> $GITHUB_ENV
        cat summary.md >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      shell: bash

    - name: Post comment to PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ env.SUMMARY }}
