name: 'Database Lab: realistic DB testing in CI'
branding:
  icon: 'database'  
  color: 'orange'
description: 'Check database migrations with the Database Lab Engine'
inputs:
  owner:
    description: 'The owner of the repository to check'
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: 'The repo to check'
    required: true
    default: ${{ github.event.repository.name }}
  ref:
    description: 'The input represents a ref parameter, which can be a SHA, branch, or tag'
    required: true
    default: ${{ github.ref }}
  pull_request:
    description: 'Link to the pull request'
    required: false
    default: ${{ github.event.pull_request.html_url }}
  compare:
    description: 'The compare link'
    required: false
    default: ${{ github.event.compare }}
  commit_sha:
    description: 'Commit SHA'
    required: false
    default: ${{ github.event.after }}
  author_name:
    description: 'Author name'
    required: false
    default: ${{ github.event.head_commit.author.name }}


outputs:
  response:
    description: 'The result of CI checks'
runs:
  using: 'docker'
  image: 'Dockerfile'
