name: 'Database Lab: realistic DB testing in CI'
branding:
  icon: 'database'  
  color: 'orange'
description: 'Check database migrations with the Database Lab Engine'
inputs:
  owner:
    description: 'Repository owner'
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: 'Repository'
    required: true
    default: ${{ github.event.repository.name }}
  ref:
    description: 'Ref (SHA, branch, or tag) that needs to be tested'
    required: true
    default: ${{ github.ref }}
  pull_request:
    description: 'GitHub PR (URL)'
    required: false
    default: ${{ github.event.pull_request.html_url }}
  compare:
    description: 'GitHub PR comparison URL'
    required: false
    default: ${{ github.event.compare }}
  commit_sha:
    description: 'Commit SHA'
    required: false
    default: ${{ github.event.after }}
  author_name:
    description: 'Author name'
    required: false
    default: ${{ github.event.head_commit.author.name }}

  commands:
    description: 'List of commands to run DB migrations'
    required: true
  dbname:
    description: 'Database name'
    required: false
    default: ""
  migration_envs:
    description: 'List of environment variables that will be set before testing'
    required: false
  download_artifacts:
    description: 'Store artifacts and allow downloading them'
    required: false
    default: "false"

  observation_interval:
    description: 'Observation interval, seconds (default: 10)'
    required: false
    default: "10"
  max_lock_duration:
    description: 'Exclusive lock duration threshold, seconds (default: 10)'
    required: false
    default: "10"
  max_duration:
    description: 'DB migration duration threshold, seconds (default: 3600)'
    required: false
    default: "3600"


outputs:
  response:
    description: 'DB migration testing results'
runs:
  using: 'docker'
  image: 'Dockerfile'
